apiVersion: v2
name: livepeer-gateway
description: Livepeer gateway chart supporting singleton and distributed modes
type: application
version: 1.0.0
appVersion: "v0.8.9"
icon: https://cdn.prod.website-files.com/660e2fe4cba2fca14e90fc61/6644be2f885be8fd1dc92233_favicon256-t.png
dependencies:
  - name: livepeer-common
    version: 1.0.0
    repository: file://../livepeer-common
