apiVersion: v2
name: livepeer-gateway
description: Livepeer gateway chart supporting singleton and distributed modes
type: application
version: 0.1.0
appVersion: "v0.8.9"
dependencies:
  - name: livepeer-common
    version: 0.1.0
    repository: file://../livepeer-common
