{{- if .Values.gateway.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "livepeer-gateway.fullname" . }}
  labels:
    {{- include "livepeer-gateway.labels" . | nindent 4 }}
  {{- with (include "livepeer-common.annotations" .Values.gateway.ingress.annotations) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.gateway.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- with .Values.gateway.ingress.tls }}
  tls:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.gateway.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType | default "ImplementationSpecific" }}
            backend:
              service:
                name: {{ include "livepeer-gateway.fullname" $ }}
                port:
                  {{- if .servicePort }}
                  number: {{ .servicePort }}
                  {{- else }}
                  name: http-video
                  {{- end }}
          {{- end }}
    {{- end }}
{{- end }}
