{{- if .Values.gateway.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "livepeer-gateway.fullname" . }}
  labels:
    {{- include "livepeer-gateway.labels" . | nindent 4 }}
  {{- with .Values.gateway.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.gateway.service.type }}
  ports:
    {{- toYaml .Values.gateway.service.ports | nindent 4 }}
  selector:
    {{- include "livepeer-gateway.selectorLabels" . | nindent 4 }}
{{- end }}
